### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by dawlab** [dawlab/marvel-comics#1]
Hej, tu jest makieta jak ta appka docelowo ma wyglądać: https://www.figma.com/proto/CET2h3XyxsvNMi8Wz2P5HW/Comics-app?node-id=101%3A1495&viewport=769%2C-1151%2C0.47655215859413147&scaling=min-zoom 

Mam jeszcze trochę do zrobienia, ale powoli już coś tam się dzieje. Robiłem od zera i starałem się do wszystkiego sam dojść. Sprawdzisz jak mi poszło? 

Zwróć uwagę na to, jak ładują się elementy do tableview: 

<img width="481" alt="Screenshot 2023-01-24 at 13 29 13" src="https://user-images.githubusercontent.com/7715561/214291917-36b0bcc7-313a-4226-b520-91ae73e35b92.png">

Zanim to się wykona to na początku jest moment, że nic sie nie wyświetla. Nie miałem pomysłu jak to inaczej obejść. Chyba musiałbym zapisać w danych wcześniej pobrane elementy, na starcie je załadować i dopiero po chwili zrobić reloadData świeżo pobranymi elementami. 

Mam też problem z navigationController - wyskakują jakieś błędy, próbowałem naprawić, ale nie do końca rozumiem. Zastanawiam się też dlaczego jak próbuję edytować atrybuty backBarButtonItem to nic się nie dzieje? Czy powinienem opakować ten DetailViewController w osobny navigationController? Nie rozumiem do końca jak to działa 

<img width="630" alt="Screenshot 2023-01-24 at 13 54 30" src="https://user-images.githubusercontent.com/7715561/214296937-d43e2ba6-8f14-47ce-938e-05c957d5cb6e.png">

Ostatnia rzecz, która jeszcze nie jest gotowa, ale daj znać, czy dobry trop - w makiecie jak wejdziesz w podgląd komiksu, to jest taki rozwijany coś jak bottom sheet. Sprawdzałem kilka rozwiązań, ale to jednak nie będzie chyba żaden dodatkowy viewcontroller tylko mogę to zrobić po prostu dodając większy uiview jako subview. Jak myślisz? Bo on nie rozwija się od samego dołu (rozwija się ponad buttonem) i nie mogę nim manipilować dowolnie, mogę tylko go powiększyć klikając w ten grabber na górze elementu. 

Daj znac ogólnie, co trzeba poprawić. Planowo appka miała być w MVC, więc starałem się tego trzymać. Ja chciałbym tę aplikację do końca tygodnia skończyć całkowicie tak żeby była zgodna z założeniami (masz je w readme tego projektu)

**Comment by twprzybysz** [comment]
Ok, mam - zerknę na to

**Comment by twprzybysz** [comment]
> Zanim to się wykona to na początku jest moment, że nic sie nie wyświetla. Nie miałem pomysłu jak to inaczej obejść. Chyba musiałbym zapisać w danych wcześniej pobrane elementy, na starcie je załadować i dopiero po chwili zrobić reloadData świeżo pobranymi elementami.

To co proponujesz to jest jedna opcja, ale wyobraź sobie że dojdą nowe elementy - wtedy będziesz miał "mignięcie" i zobaczysz nowe elementy - z jednego problemu wpadniesz drugi.
Rozwiązaniem jest ekran ładowania, shimmering bądź coś co zasugeruje że dane się ładują.

> Ostatnia rzecz, która jeszcze nie jest gotowa, ale daj znać, czy dobry trop - w makiecie jak wejdziesz w podgląd komiksu, to jest taki rozwijany coś jak bottom sheet. Sprawdzałem kilka rozwiązań, ale to jednak nie będzie chyba żaden dodatkowy viewcontroller tylko mogę to zrobić po prostu dodając większy uiview jako subview. Jak myślisz? Bo on nie rozwija się od samego dołu (rozwija się ponad buttonem) i nie mogę nim manipilować dowolnie, mogę tylko go powiększyć klikając w ten grabber na górze elementu.

Różnie to się robi - czasem to jest view, czasem może być view controller - zazwyczaj to kwestia potrzeb, spróbuj z view póki co będzie prościej.

> Mam też problem z navigationController - wyskakują jakieś błędy, próbowałem naprawić, ale nie do końca rozumiem. Zastanawiam się też dlaczego jak próbuję edytować atrybuty backBarButtonItem to nic się nie dzieje? Czy powinienem opakować ten DetailViewController w osobny navigationController? Nie rozumiem do końca jak to działa

Co do kodu to się nie uruchamia - mam błąd: No such module 'FloatingPanel'

**Comment by twprzybysz** [comment]
Skąd pochodzi to zadanie? @dawlab

**Comment by dawlab** [comment]
> Co do kodu to się nie uruchamia - mam błąd: No such module 'FloatingPanel'

Co ja robię nie tak, że czasami u mnie działa normalnie a u Ciebie nie? Bo faktycznie instalowałem takie coś jak Floating Panel, ale potem to usunąłem z Package Dependencies. U mnie działa nawet jak dam erase all content and settings w symulatorze

**Comment by dawlab** [comment]
> Skąd pochodzi to zadanie? @dawlab

To jest zadanie rekrutacyjne na juniora, ktoś to wrzucił na którąś z grup dla początkujących programistów, chyba tutaj: https://www.facebook.com/groups/1561984417428846

**Comment by dawlab** [comment]
> Rozwiązaniem jest ekran ładowania, shimmering bądź coś co zasugeruje że dane się ładują.
> 
> >

No w sumie proste, a nie wpadłem na to. Spróbuję coś takiego zrobić

**Comment by twprzybysz** [comment]
> Co ja robię nie tak, że czasami u mnie działa normalnie a u Ciebie nie? Bo faktycznie instalowałem takie coś jak Floating Panel, ale potem to usunąłem z Package Dependencies. U mnie działa nawet jak dam erase all content and settings w symulatorze

1. Brak .gitignore
2. Nie wiedzieć czemu u Ciebie mocno trzyma cache polecam DevCleaner
3. Brak zewnętrznego systemu do budowania (jakieś CI)

Wywaliłem ten import i działa, patrzę.

**Comment by twprzybysz** [comment]
Wrzuć ten kod do viewDidLoad do pierwszego VC, natomiast z details wywal.

```
    let image = UIImage(named: "arrow.backward")
    navigationController?.navigationBar.backIndicatorImage = image
    navigationController?.navigationBar.backIndicatorTransitionMaskImage = image
        
    navigationItem.backButtonDisplayMode = .minimal
```

Zapytasz dlaczego tak? Po 1 - to co próbowałeś zrobić to ustawić obrazek na "Nullu" - polecam debuggera. Po 2 - "własności" opierają się o gotowe rzeczy ktore daje z pudełka apple - trochę czasu minie nim się z tym człowiek oswoi.

Tutaj dokumentacja navbara https://developer.apple.com/documentation/uikit/uinavigationbar a tu navigationVC https://developer.apple.com/documentation/uikit/uinavigationcontroller/

**Comment by dawlab** [comment]
update: dodałem custom view, jak się stuknie lub zrobi swipe up na opisie to view się powiększa.

**Comment by dawlab** [comment]
No dobra, za szybko się ucieszyłem. Na nowych wygląda dobrze, na iPhone 8/SE jest źle - poprawię

**Comment by twprzybysz** [comment]
Gitignore powinien być na wyższym poziomie a nie w środku projektu

**Comment by twprzybysz** [comment]
Dobra to lecą uwagi w związku z tym kodem:

Na plus:
- dosyć ładny UX, miejscami można dopracować (np tytuły się skalują jak jest jeszcze miejsce), ale to jest kosmetyka - ogólnie dopracowując te aspekty UX możesz potencjalnie błysnąć na każdej rozmowie bo u Ciebie to jest atut. Pamiętaj że to nie jest najważniejszy aspekt i można o niego zadbać gdy rzeczywiście masz ekstra czas.
- dobrze użyte storyboardy i xiby (można poprawić czytelność nazywając elementy bardziej domenowe a nie że się wyświetla "Tab bar Controller Scene)
- jest pewien podział - Modele, Widoki, Controllery, Managery

Na minus:
- Mało tego SOLID widać, w ComicsManager jest solid jest złamany
- Parsowanie jest "ok", ale można to poprawić zwłaszcza jeżeli chodzi o czytelność i jakość całego rozwiązania - dlaczego structy oznaczone Decodable są var? 
- Popracować nad formatowaniem (extra entery, dziwne wcięcia, zakomentowany i nieużywany kod)
- Search jest niezaimplementowany

Ogólnie - widać że kumasz, trzeba mocno popracować nad "jakością" i formą - powinno być ok.
@dawlab

**Comment by dawlab** [comment]
@twprzybysz tutaj mam problem i nie wiem jak do tego podejść: https://github.com/dawlab/marvel-comics/pull/2
